version: '3.3'
 
services:
    jenkins:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-}
                CONTAINER_NAME: jenkins
                CONTAINER_VERSION: ${CONTAINER_VERSION:-3.0.0}
                FROM_BASE: ${DOCKER_REGISTRY:-}${OS:-}openjdk/8.171.11-r0:${BASE_TAG:-latest}
                JENKINS_HOME: ${JENKINS_HOME:-/var/jenkins_home}
                docker_gid: 999
                docker_uid: 999
                jenkins_gid: 1000
                jenkins_uid: 1004
            cache_from:
                - ${DOCKER_REGISTRY:-}${OS:-}alpine:3.8
                - ${DOCKER_REGISTRY:-}${OS:-}base_container:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-}${OS:-}openjdk/8.171.11-r0:${BASE_TAG:-latest}
            context: .
            dockerfile: Dockerfile
            labels:
                container.build.time: $CONTAINER_BUILD_TIME
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.refs: $CONTAINER_GIT_REFS
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: jenkins
        container_name: jenkins
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            JENKINS_GITHUB_EMAIL: $CFG_GITHUB_JENKINS_EMAIL
            JENKINS_GITHUB_NAME: $CFG_GITHUB_JENKINS_NAME
            JENKINS_GITHUB_CREDENTIALS: "${CFG_GITHUB_JENKINS_USER}:${CFG_GITHUB_JENKINS_TOKEN}"
        hostname: jenkins
        image: ${DOCKER_REGISTRY:-}${OS:-}jenkins/2.121.3:${CONTAINER_TAG:-latest}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:
            - 8080:8080
        volumes:
            - ./vols/jenkins_home:/var/jenkins_home
            - ~/.ssh:/var/ssh
            - ./vols/log:/var/log/jenkins
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/bin/docker:/usr/bin/docker
