version: '3.5'
 
services:
    jenkins:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-dev}
                CONTAINER_NAME: jenkins
                CONTAINER_VERSION: 1.0.7
                DEBUG_TRACE: 0
                FROM_BASE: openjdk_8u131.11-r2:latest
                JENKINS_HOME: ${JENKINS_HOME:-/var/jenkins_home}
                docker_gid: 999
                docker_uid: 999
                jenkins_gid: 1953
                jenkins_uid: 1953
            cache_from:
                - alpine:3.6
                - base_container:latest
                - openjdk_8u131.11-r2:latest
            context: .
            dockerfile: Dockerfile
        container_name: jenkins
        environment:
            JENKINS_GITHUB_EMAIL: ${CFG_GITHUB_JENKINS_EMAIL}
            JENKINS_GITHUB_NAME: ${CFG_GITHUB_JENKINS_NAME}
            JENKINS_GITHUB_CREDENTIALS: "${CFG_GITHUB_JENKINS_USER}:${CFG_GITHUB_JENKINS_TOKEN}"
        hostname: jenkins
        image: jenkins:latest
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:
            - 8080:8080
#        restart: unless-stopped
        volumes:
            - ./vols/jenkins_home:/var/jenkins_home
            - ./vols/.ssh:/var/jenkins_home/.ssh
            - ./vols/log:/var/log/jenkins
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/bin/docker:/usr/bin/docker
