version: '3.3'

# this is a SAMPLE file. Do not use for build or deployments

# use the following to restrict which OS this is built on
# containerOS: alpine

services:
    jenkins:
        build:
# build arguements
            args:
                CBF_VERSION: ${CBF_VERSION:-}
                CONTAINER_NAME: jenkins
                JENKINS_VERSION: ${JENKINS_VERSION:-2.138.2}
                FROM_BASE: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/openjdk/${JAVA_VERSION:-8.171.11-r0}:${BASE_TAG:-latest}
                JENKINS_HOME: ${JENKINS_HOME:-/var/jenkins_home}
                docker_gid: 999
                docker_uid: 999
                jenkins_gid: 1000
                jenkins_uid: 1004
            cache_from:
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}thirdparty/${CONTAINER_OS:-alpine}:${OS_VERSION:-3.12.0}
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/base_container:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/openjdk/${JAVA_VERSION:-8.171.11-r0}:${BASE_TAG:-latest}
            context: .
            dockerfile: Dockerfile
            labels:
                container.build.time: $CONTAINER_BUILD_TIME
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.refs: $CONTAINER_GIT_REFS
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: jenkins
                version.cbf: $CBF_VERSION
        container_name: jenkins
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
# git references used by scm-sync-plugin only
            JENKINS_GITHUB_EMAIL: $CFG_JENKINS_EMAIL
            JENKINS_GITHUB_NAME: $CFG_JENKINS_NAME
            JENKINS_GITHUB_CREDENTIALS_FILE: /run/secrets/github.credentials
# JVM options
#            JAVA_OPTS: "-Xmx2048m -XX:MaxPermSize=512m"
            CASC_JENKINS_CONFIG: /var/jenkins_home/casc_configs
        hostname: jenkins
        image: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/jenkins/${JENKINS_VERSION:-2.138.1}:${CONTAINER_TAG:-latest}
# limit size of logs @runtime so that we do not run out of space
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
#ports exposed
        ports:
            - 8080:8080
# references to 'secrets' section below
        secrets:
            - github.credentials
        volumes:
# JENKINS_HOME
            - ./vols/jenkins_home:/var/jenkins_home
# locaation of 'configuration As Code'
            - ./vols/casc_configs:/var/jenkins_home/casc_configs
# ability to use non-default certs
            - ./vols/ssl:/usr/local/share/ca-certificates
# do not save jenkins logs inside container
            - ./vols/log:/var/log/jenkins
# provide access to credentials for 'scm-sync-plugin'
            - ~/.ssh:/var/ssh
# share docker.sock to permit use of docker side-cars
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/bin/docker:/usr/bin/docker
secrets:
# location of secrets files in host filesystem
   github.credentials:
     file: ~/.secrets/github.credentials
