version: '3.1'

services:
    jenkins:
        build:
            context: ../jenkins
            args:
                TZ: "America/New_York"
                JENKINS_GITHUB_EMAIL: ${CFG_GITHUB_JENKINS_EMAIL}
                JENKINS_GITHUB_NAME: ${CFG_GITHUB_JENKINS_NAME}
                JENKINS_GITHUB_TOKEN: ${CFG_GITHUB_JENKINS_TOKEN}
                JENKINS_GITHUB_USER: ${CFG_GITHUB_JENKINS_USER}
        image: jenkins:20170916
        container_name: jenkins
        hostname: jenkins
        restart: unless-stopped
        environment:
            TZ: "America/New_York"
            JAVA_OPTS: "-Djava.util.logging.config.file=/var/jenkins_home/log.properties -Djenkins.install.runSetupWizard=false"
            JENKINS_GITHUB_EMAIL: ${CFG_GITHUB_JENKINS_EMAIL}
            JENKINS_GITHUB_NAME: ${CFG_GITHUB_JENKINS_NAME}
            JENKINS_GITHUB_TOKEN: ${CFG_GITHUB_JENKINS_TOKEN}
            JENKINS_GITHUB_USER: ${CFG_GITHUB_JENKINS_USER}
            JENKINS_HOME: /var/jenkins_home
            JENKINS_OPTS: "--prefix=/jenkins"
        volumes:
            - ../jenkins/jenkins_home:/var/jenkins_home
            - ../jenkins/container/.ssh:/var/jenkins_home/.ssh
           #- ../jenkins/container/.gitconfig:/var/jenkins_home/.gitconfig
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/bin/docker:/usr/bin/docker
        ports:
            - 8080:8080
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
