version: '3.3'
 
# repo: https://github/ballab1/jenkins.git
# containerOS: alpine

services:
    jenkins:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-}
                CONTAINER_NAME: jenkins
                JENKINS_VERSION: ${JENKINS_VERSION:-2.277.4}
                FROM_BASE: ${DOCKER_REGISTRY:-s2.ubuntu.home:5000/}${CONTAINER_OS:-alpine}/openjdk/${JAVA_VERSION:-11.0.11_p9-r0}:${BASE_TAG:-latest}
                JENKINS_HOME: ${JENKINS_HOME:-/var/jenkins_home}
                docker_gid: 999
                docker_uid: 999
                jenkins_gid: 1004
                jenkins_uid: 1000
            cache_from:
                - ${DOCKER_REGISTRY:-s2.ubuntu.home:5000/}thirdparty/${CONTAINER_OS:-alpine}:${OS_VERSION:-3.14.0}
                - ${DOCKER_REGISTRY:-s2.ubuntu.home:5000/}${CONTAINER_OS:-alpine}/base_container:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-s2.ubuntu.home:5000/}${CONTAINER_OS:-alpine}/openjdk/${JAVA_VERSION:-11.0.11_p9-r0}:${BASE_TAG:-latest}
            context: .
            dockerfile: Dockerfile
            labels:
                container.build.time: $CONTAINER_BUILD_TIME
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.refs: $CONTAINER_GIT_REFS
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: jenkins
                container.parent: $CONTAINER_PARENT
                version.cbf: $CBF_VERSION
        container_name: jenkins
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            CASC_JENKINS_CONFIG: /var/jenkins_home/casc_configs
        hostname: jenkins
        image: ${DOCKER_REGISTRY:-s2.ubuntu.home:5000/}${CONTAINER_OS:-alpine}/jenkins/${JENKINS_VERSION:-2.319.3}:${CONTAINER_TAG:-latest}
